# GENERAL
EXIT = 0
PREVIOUS_MENU = 0
CHECK_CONFIRMATION = ["y","n"]
CHECK_YES = "y"
CHECK_NO = "n"
PROGRAM_ON = 1
PROGRAM_OFF = 0

# MAIN
SHOW_ALL = 1
WALLET_OPTIONS = 2
OPTIONS = 3
MAIN_ACTION_LIST = [
    SHOW_ALL,
    WALLET_OPTIONS,
    OPTIONS
]

# SHOW ALL OPTIONS

# WALLET OPTIONS
SHOW_WALLET = 1
CHANGE_ANY_AMMOUNT = 2
ADD_CRYPTO = 3
UPDATE_WALLET = 4
WALLET_ACTION_LIST = [
    SHOW_WALLET,
    CHANGE_ANY_AMMOUNT,
    ADD_CRYPTO,
    UPDATE_WALLET
]
INVALID_PRICE = 0.0
ROUND_TO_FOUR = ["default_allocation", "growth_fiat", "growth_interest"]
ROUND_TO_SIX = ["ammount_bought", "ammount_now", "interest_earned"]

# OPTIONS
CHANGE_WALLET_REFRESH_TIME = 1
OPTIONS_ACTION_LIST = [
    CHANGE_WALLET_REFRESH_TIME
]
CHANGE_TIME_MINUTES_STR = ["15 Minutes", "30 Minutes", "1 Hour", "24 Hours"]
CHANGE_TIME_MINUTES_INPUT = [1, 2, 3, 4]
CHANGE_TIME_MINUTES_MIN = [15, 30, 60, 1440]